name: Go Multi-Platform Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
          - os: linux
            arch: amd64
            cgo: 1  # 启用 CGO
          - os: linux
            arch: arm64
            cgo: 1  # 启用 CGO
          - os: windows
            arch: amd64
            cgo: 0  # Windows 通常不需要 CGO
          - os: darwin
            arch: amd64
            cgo: 0  # macOS 通常不需要 CGO
          - os: darwin
            arch: arm64
            cgo: 0  # macOS 通常不需要 CGO

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 仅 Linux 需要安装依赖
      - name: Install Linux dependencies
        if: matrix.build.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.23.0'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          OUTPUT="click-${{ matrix.build.os }}-${{ matrix.build.arch }}"
          if [ "${{ matrix.build.os }}" = "windows" ]; then
            OUTPUT="$OUTPUT.exe"
          fi
          
          # 使用矩阵中的 CGO 设置
          CGO_ENABLED=${{ matrix.build.cgo }} \
          GOOS=${{ matrix.build.os }} \
          GOARCH=${{ matrix.build.arch }} \
          go build -o "./dist/$OUTPUT" main.go

      - name: Archive artifact
        if: matrix.build.os != 'windows'
        run: |
          cd dist
          tar czf click-${{ matrix.build.os }}-${{ matrix.build.arch }}.tar.gz \
            click-${{ matrix.build.os }}-${{ matrix.build.arch }}

      - name: Archive Windows artifact
        if: matrix.build.os == 'windows'
        run: |
          cd dist
          zip click-windows-amd64.zip click-windows-amd64.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: click-${{ matrix.build.os }}-${{ matrix.build.arch }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Collect release assets
        run: |
          mkdir release-assets
          find artifacts -name '*.tar.gz' -exec cp {} release-assets/ \;
          find artifacts -name '*.zip' -exec cp {} release-assets/ \;

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}